id: P006945
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG2818
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོའི་རང་ཞལ་མངོན་དུ་བྱེད་པའི་གདམས་པ་ཟབ་གསང་སྙིང་པོ
  author: ''
  volumes:
    bc244758757e4a0f8da15641e2be6406:
      image_group_id: I1KG3159
      title: ''
      volume_number: 1
      total_pages: 116
ebook_metadata:
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོའི་རང་ཞལ་མངོན་དུ་བྱེད་པའི་གདམས་པ་ཟབ་གསང་སྙིང་པོ
  author: ''
  sku: P006945
  cover: cover.jpg
  layers:
  - pagination
