id: I3766E881
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:29:50+00:00'
last_modified: '2022-06-08T12:47:45.514505+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG2818
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོའི་རང་ཞལ་མངོན་དུ་བྱེད་པའི་གདམས་པ་ཟབ་གསང་སྙིང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8402':
      image_group_id: I1KG3159
      title: Volume 1 of rang bzhin rdzogs pa chen po'i rang zhal mngon du byed pa'i
        gdams pa zab gsang snying po
      total_pages: 116
      order: 1
      base_file: 8402.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
